databases:
  - name: johnnyspieshop
    plan: free
    databaseName: YOURAPPNAME
    user: YOURAPPNAME

services:
  - type: web
    name: YOURAPPNAME
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: YOURAPPNAME
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
